from dataclasses import dataclass

@dataclass(frozen=True)
class FeatureDefinition:
    index: int
    key: str
    display: str
    group: str
    lower: float
    upper: float
    unit: str
    required: bool

RADIOLOGY = (
    FeatureDefinition(0, "atelectasis_00", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(1, "cardiomegaly_00", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(2, "effusion_00", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(3, "infiltration_00", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(4, "mass_00", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(5, "nodule_00", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(6, "pneumonia_00", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(7, "pneumothorax_00", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(8, "consolidation_00", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(9, "edema_00", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(10, "emphysema_00", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(11, "fibrosis_00", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(12, "pleural_thickening_00", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(13, "hernia_00", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(14, "atelectasis_01", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(15, "cardiomegaly_01", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(16, "effusion_01", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(17, "infiltration_01", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(18, "mass_01", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(19, "nodule_01", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(20, "pneumonia_01", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(21, "pneumothorax_01", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(22, "consolidation_01", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(23, "edema_01", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(24, "emphysema_01", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(25, "fibrosis_01", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(26, "pleural_thickening_01", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(27, "hernia_01", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(28, "atelectasis_02", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(29, "cardiomegaly_02", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(30, "effusion_02", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(31, "infiltration_02", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(32, "mass_02", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(33, "nodule_02", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(34, "pneumonia_02", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(35, "pneumothorax_02", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(36, "consolidation_02", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(37, "edema_02", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(38, "emphysema_02", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(39, "fibrosis_02", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(40, "pleural_thickening_02", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(41, "hernia_02", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(42, "atelectasis_03", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(43, "cardiomegaly_03", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(44, "effusion_03", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(45, "infiltration_03", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(46, "mass_03", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(47, "nodule_03", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(48, "pneumonia_03", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(49, "pneumothorax_03", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(50, "consolidation_03", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(51, "edema_03", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(52, "emphysema_03", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(53, "fibrosis_03", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(54, "pleural_thickening_03", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(55, "hernia_03", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(56, "atelectasis_04", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(57, "cardiomegaly_04", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(58, "effusion_04", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(59, "infiltration_04", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(60, "mass_04", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(61, "nodule_04", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(62, "pneumonia_04", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(63, "pneumothorax_04", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(64, "consolidation_04", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(65, "edema_04", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(66, "emphysema_04", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(67, "fibrosis_04", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(68, "pleural_thickening_04", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(69, "hernia_04", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(70, "atelectasis_05", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(71, "cardiomegaly_05", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(72, "effusion_05", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(73, "infiltration_05", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(74, "mass_05", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(75, "nodule_05", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(76, "pneumonia_05", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(77, "pneumothorax_05", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(78, "consolidation_05", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(79, "edema_05", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(80, "emphysema_05", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(81, "fibrosis_05", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(82, "pleural_thickening_05", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(83, "hernia_05", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(84, "atelectasis_06", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(85, "cardiomegaly_06", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(86, "effusion_06", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(87, "infiltration_06", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(88, "mass_06", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(89, "nodule_06", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(90, "pneumonia_06", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(91, "pneumothorax_06", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(92, "consolidation_06", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(93, "edema_06", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(94, "emphysema_06", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(95, "fibrosis_06", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(96, "pleural_thickening_06", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(97, "hernia_06", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(98, "atelectasis_07", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(99, "cardiomegaly_07", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(100, "effusion_07", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(101, "infiltration_07", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(102, "mass_07", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(103, "nodule_07", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(104, "pneumonia_07", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(105, "pneumothorax_07", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(106, "consolidation_07", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(107, "edema_07", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(108, "emphysema_07", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(109, "fibrosis_07", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(110, "pleural_thickening_07", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(111, "hernia_07", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(112, "atelectasis_08", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(113, "cardiomegaly_08", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(114, "effusion_08", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(115, "infiltration_08", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(116, "mass_08", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(117, "nodule_08", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(118, "pneumonia_08", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(119, "pneumothorax_08", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(120, "consolidation_08", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(121, "edema_08", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(122, "emphysema_08", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(123, "fibrosis_08", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(124, "pleural_thickening_08", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(125, "hernia_08", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(126, "atelectasis_09", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(127, "cardiomegaly_09", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(128, "effusion_09", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(129, "infiltration_09", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(130, "mass_09", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(131, "nodule_09", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(132, "pneumonia_09", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(133, "pneumothorax_09", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(134, "consolidation_09", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(135, "edema_09", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(136, "emphysema_09", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(137, "fibrosis_09", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(138, "pleural_thickening_09", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(139, "hernia_09", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(140, "atelectasis_10", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(141, "cardiomegaly_10", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(142, "effusion_10", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(143, "infiltration_10", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(144, "mass_10", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(145, "nodule_10", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(146, "pneumonia_10", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(147, "pneumothorax_10", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(148, "consolidation_10", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(149, "edema_10", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(150, "emphysema_10", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(151, "fibrosis_10", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(152, "pleural_thickening_10", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(153, "hernia_10", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(154, "atelectasis_11", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(155, "cardiomegaly_11", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(156, "effusion_11", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(157, "infiltration_11", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(158, "mass_11", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(159, "nodule_11", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(160, "pneumonia_11", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(161, "pneumothorax_11", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(162, "consolidation_11", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(163, "edema_11", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(164, "emphysema_11", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(165, "fibrosis_11", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(166, "pleural_thickening_11", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(167, "hernia_11", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(168, "atelectasis_12", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(169, "cardiomegaly_12", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(170, "effusion_12", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(171, "infiltration_12", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(172, "mass_12", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(173, "nodule_12", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(174, "pneumonia_12", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(175, "pneumothorax_12", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(176, "consolidation_12", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(177, "edema_12", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(178, "emphysema_12", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(179, "fibrosis_12", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(180, "pleural_thickening_12", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(181, "hernia_12", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(182, "atelectasis_13", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(183, "cardiomegaly_13", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(184, "effusion_13", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(185, "infiltration_13", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(186, "mass_13", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(187, "nodule_13", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(188, "pneumonia_13", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(189, "pneumothorax_13", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(190, "consolidation_13", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(191, "edema_13", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(192, "emphysema_13", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(193, "fibrosis_13", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(194, "pleural_thickening_13", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(195, "hernia_13", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(196, "atelectasis_14", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(197, "cardiomegaly_14", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(198, "effusion_14", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(199, "infiltration_14", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(200, "mass_14", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(201, "nodule_14", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(202, "pneumonia_14", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(203, "pneumothorax_14", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(204, "consolidation_14", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(205, "edema_14", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(206, "emphysema_14", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(207, "fibrosis_14", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(208, "pleural_thickening_14", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(209, "hernia_14", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(210, "atelectasis_15", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(211, "cardiomegaly_15", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(212, "effusion_15", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(213, "infiltration_15", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(214, "mass_15", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(215, "nodule_15", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(216, "pneumonia_15", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(217, "pneumothorax_15", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(218, "consolidation_15", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(219, "edema_15", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(220, "emphysema_15", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(221, "fibrosis_15", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(222, "pleural_thickening_15", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(223, "hernia_15", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(224, "atelectasis_16", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(225, "cardiomegaly_16", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(226, "effusion_16", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(227, "infiltration_16", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(228, "mass_16", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(229, "nodule_16", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(230, "pneumonia_16", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(231, "pneumothorax_16", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(232, "consolidation_16", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(233, "edema_16", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(234, "emphysema_16", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(235, "fibrosis_16", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(236, "pleural_thickening_16", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(237, "hernia_16", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(238, "atelectasis_17", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(239, "cardiomegaly_17", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(240, "effusion_17", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(241, "infiltration_17", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(242, "mass_17", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(243, "nodule_17", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(244, "pneumonia_17", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(245, "pneumothorax_17", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(246, "consolidation_17", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(247, "edema_17", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(248, "emphysema_17", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(249, "fibrosis_17", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(250, "pleural_thickening_17", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(251, "hernia_17", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(252, "atelectasis_18", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(253, "cardiomegaly_18", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(254, "effusion_18", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(255, "infiltration_18", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(256, "mass_18", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(257, "nodule_18", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(258, "pneumonia_18", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(259, "pneumothorax_18", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(260, "consolidation_18", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(261, "edema_18", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(262, "emphysema_18", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(263, "fibrosis_18", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(264, "pleural_thickening_18", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(265, "hernia_18", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(266, "atelectasis_19", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(267, "cardiomegaly_19", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(268, "effusion_19", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(269, "infiltration_19", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(270, "mass_19", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(271, "nodule_19", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(272, "pneumonia_19", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(273, "pneumothorax_19", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(274, "consolidation_19", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(275, "edema_19", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(276, "emphysema_19", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(277, "fibrosis_19", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(278, "pleural_thickening_19", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(279, "hernia_19", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(280, "atelectasis_20", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(281, "cardiomegaly_20", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(282, "effusion_20", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(283, "infiltration_20", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(284, "mass_20", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(285, "nodule_20", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(286, "pneumonia_20", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(287, "pneumothorax_20", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(288, "consolidation_20", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(289, "edema_20", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(290, "emphysema_20", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(291, "fibrosis_20", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(292, "pleural_thickening_20", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(293, "hernia_20", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(294, "atelectasis_21", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(295, "cardiomegaly_21", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(296, "effusion_21", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(297, "infiltration_21", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(298, "mass_21", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(299, "nodule_21", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(300, "pneumonia_21", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(301, "pneumothorax_21", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(302, "consolidation_21", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(303, "edema_21", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(304, "emphysema_21", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(305, "fibrosis_21", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(306, "pleural_thickening_21", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(307, "hernia_21", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(308, "atelectasis_22", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(309, "cardiomegaly_22", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(310, "effusion_22", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(311, "infiltration_22", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(312, "mass_22", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(313, "nodule_22", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(314, "pneumonia_22", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(315, "pneumothorax_22", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(316, "consolidation_22", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(317, "edema_22", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(318, "emphysema_22", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(319, "fibrosis_22", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(320, "pleural_thickening_22", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(321, "hernia_22", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(322, "atelectasis_23", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(323, "cardiomegaly_23", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(324, "effusion_23", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(325, "infiltration_23", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(326, "mass_23", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(327, "nodule_23", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(328, "pneumonia_23", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(329, "pneumothorax_23", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(330, "consolidation_23", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(331, "edema_23", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(332, "emphysema_23", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(333, "fibrosis_23", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(334, "pleural_thickening_23", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(335, "hernia_23", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(336, "atelectasis_24", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(337, "cardiomegaly_24", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(338, "effusion_24", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(339, "infiltration_24", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(340, "mass_24", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(341, "nodule_24", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(342, "pneumonia_24", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(343, "pneumothorax_24", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(344, "consolidation_24", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(345, "edema_24", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(346, "emphysema_24", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(347, "fibrosis_24", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(348, "pleural_thickening_24", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(349, "hernia_24", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(350, "atelectasis_25", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(351, "cardiomegaly_25", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(352, "effusion_25", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(353, "infiltration_25", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(354, "mass_25", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(355, "nodule_25", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(356, "pneumonia_25", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(357, "pneumothorax_25", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(358, "consolidation_25", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(359, "edema_25", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(360, "emphysema_25", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(361, "fibrosis_25", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(362, "pleural_thickening_25", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(363, "hernia_25", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(364, "atelectasis_26", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(365, "cardiomegaly_26", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(366, "effusion_26", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(367, "infiltration_26", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(368, "mass_26", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(369, "nodule_26", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(370, "pneumonia_26", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(371, "pneumothorax_26", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(372, "consolidation_26", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(373, "edema_26", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(374, "emphysema_26", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(375, "fibrosis_26", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(376, "pleural_thickening_26", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(377, "hernia_26", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(378, "atelectasis_27", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(379, "cardiomegaly_27", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(380, "effusion_27", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(381, "infiltration_27", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(382, "mass_27", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(383, "nodule_27", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(384, "pneumonia_27", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(385, "pneumothorax_27", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(386, "consolidation_27", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(387, "edema_27", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(388, "emphysema_27", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(389, "fibrosis_27", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(390, "pleural_thickening_27", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(391, "hernia_27", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(392, "atelectasis_28", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(393, "cardiomegaly_28", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(394, "effusion_28", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(395, "infiltration_28", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(396, "mass_28", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(397, "nodule_28", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(398, "pneumonia_28", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(399, "pneumothorax_28", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(400, "consolidation_28", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(401, "edema_28", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(402, "emphysema_28", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(403, "fibrosis_28", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(404, "pleural_thickening_28", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(405, "hernia_28", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(406, "atelectasis_29", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(407, "cardiomegaly_29", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(408, "effusion_29", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(409, "infiltration_29", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(410, "mass_29", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(411, "nodule_29", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(412, "pneumonia_29", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(413, "pneumothorax_29", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(414, "consolidation_29", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(415, "edema_29", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(416, "emphysema_29", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(417, "fibrosis_29", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(418, "pleural_thickening_29", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(419, "hernia_29", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(420, "atelectasis_30", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(421, "cardiomegaly_30", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(422, "effusion_30", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(423, "infiltration_30", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(424, "mass_30", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(425, "nodule_30", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(426, "pneumonia_30", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(427, "pneumothorax_30", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(428, "consolidation_30", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(429, "edema_30", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(430, "emphysema_30", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(431, "fibrosis_30", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(432, "pleural_thickening_30", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(433, "hernia_30", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(434, "atelectasis_31", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(435, "cardiomegaly_31", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(436, "effusion_31", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(437, "infiltration_31", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(438, "mass_31", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(439, "nodule_31", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(440, "pneumonia_31", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(441, "pneumothorax_31", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(442, "consolidation_31", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(443, "edema_31", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(444, "emphysema_31", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(445, "fibrosis_31", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(446, "pleural_thickening_31", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(447, "hernia_31", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(448, "atelectasis_32", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(449, "cardiomegaly_32", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(450, "effusion_32", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(451, "infiltration_32", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(452, "mass_32", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(453, "nodule_32", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(454, "pneumonia_32", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(455, "pneumothorax_32", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(456, "consolidation_32", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(457, "edema_32", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(458, "emphysema_32", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(459, "fibrosis_32", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(460, "pleural_thickening_32", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(461, "hernia_32", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(462, "atelectasis_33", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(463, "cardiomegaly_33", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(464, "effusion_33", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(465, "infiltration_33", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(466, "mass_33", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(467, "nodule_33", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(468, "pneumonia_33", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(469, "pneumothorax_33", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(470, "consolidation_33", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(471, "edema_33", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(472, "emphysema_33", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(473, "fibrosis_33", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(474, "pleural_thickening_33", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(475, "hernia_33", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(476, "atelectasis_34", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(477, "cardiomegaly_34", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(478, "effusion_34", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(479, "infiltration_34", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(480, "mass_34", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(481, "nodule_34", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(482, "pneumonia_34", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(483, "pneumothorax_34", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(484, "consolidation_34", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(485, "edema_34", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(486, "emphysema_34", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(487, "fibrosis_34", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(488, "pleural_thickening_34", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(489, "hernia_34", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(490, "atelectasis_35", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(491, "cardiomegaly_35", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(492, "effusion_35", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(493, "infiltration_35", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(494, "mass_35", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(495, "nodule_35", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(496, "pneumonia_35", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(497, "pneumothorax_35", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(498, "consolidation_35", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(499, "edema_35", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(500, "emphysema_35", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(501, "fibrosis_35", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(502, "pleural_thickening_35", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(503, "hernia_35", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(504, "atelectasis_36", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(505, "cardiomegaly_36", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(506, "effusion_36", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(507, "infiltration_36", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(508, "mass_36", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(509, "nodule_36", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(510, "pneumonia_36", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(511, "pneumothorax_36", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(512, "consolidation_36", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(513, "edema_36", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(514, "emphysema_36", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(515, "fibrosis_36", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(516, "pleural_thickening_36", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(517, "hernia_36", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(518, "atelectasis_37", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(519, "cardiomegaly_37", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(520, "effusion_37", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(521, "infiltration_37", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(522, "mass_37", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(523, "nodule_37", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(524, "pneumonia_37", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(525, "pneumothorax_37", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(526, "consolidation_37", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(527, "edema_37", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(528, "emphysema_37", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(529, "fibrosis_37", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(530, "pleural_thickening_37", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(531, "hernia_37", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(532, "atelectasis_38", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(533, "cardiomegaly_38", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(534, "effusion_38", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(535, "infiltration_38", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(536, "mass_38", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(537, "nodule_38", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(538, "pneumonia_38", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(539, "pneumothorax_38", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(540, "consolidation_38", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(541, "edema_38", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(542, "emphysema_38", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(543, "fibrosis_38", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(544, "pleural_thickening_38", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(545, "hernia_38", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(546, "atelectasis_39", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(547, "cardiomegaly_39", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(548, "effusion_39", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(549, "infiltration_39", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(550, "mass_39", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(551, "nodule_39", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(552, "pneumonia_39", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(553, "pneumothorax_39", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(554, "consolidation_39", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(555, "edema_39", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(556, "emphysema_39", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(557, "fibrosis_39", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(558, "pleural_thickening_39", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(559, "hernia_39", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(560, "atelectasis_40", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(561, "cardiomegaly_40", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(562, "effusion_40", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(563, "infiltration_40", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(564, "mass_40", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(565, "nodule_40", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(566, "pneumonia_40", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(567, "pneumothorax_40", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(568, "consolidation_40", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(569, "edema_40", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(570, "emphysema_40", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(571, "fibrosis_40", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(572, "pleural_thickening_40", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(573, "hernia_40", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(574, "atelectasis_41", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(575, "cardiomegaly_41", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(576, "effusion_41", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(577, "infiltration_41", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(578, "mass_41", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(579, "nodule_41", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(580, "pneumonia_41", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(581, "pneumothorax_41", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(582, "consolidation_41", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(583, "edema_41", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(584, "emphysema_41", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(585, "fibrosis_41", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(586, "pleural_thickening_41", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(587, "hernia_41", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(588, "atelectasis_42", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(589, "cardiomegaly_42", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(590, "effusion_42", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(591, "infiltration_42", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(592, "mass_42", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(593, "nodule_42", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(594, "pneumonia_42", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(595, "pneumothorax_42", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(596, "consolidation_42", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(597, "edema_42", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(598, "emphysema_42", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(599, "fibrosis_42", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(600, "pleural_thickening_42", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(601, "hernia_42", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(602, "atelectasis_43", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(603, "cardiomegaly_43", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(604, "effusion_43", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(605, "infiltration_43", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(606, "mass_43", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(607, "nodule_43", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(608, "pneumonia_43", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(609, "pneumothorax_43", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(610, "consolidation_43", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(611, "edema_43", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(612, "emphysema_43", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(613, "fibrosis_43", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(614, "pleural_thickening_43", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(615, "hernia_43", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(616, "atelectasis_44", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(617, "cardiomegaly_44", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(618, "effusion_44", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(619, "infiltration_44", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(620, "mass_44", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(621, "nodule_44", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(622, "pneumonia_44", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(623, "pneumothorax_44", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(624, "consolidation_44", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(625, "edema_44", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(626, "emphysema_44", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(627, "fibrosis_44", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(628, "pleural_thickening_44", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(629, "hernia_44", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(630, "atelectasis_45", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(631, "cardiomegaly_45", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(632, "effusion_45", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(633, "infiltration_45", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(634, "mass_45", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(635, "nodule_45", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(636, "pneumonia_45", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(637, "pneumothorax_45", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(638, "consolidation_45", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(639, "edema_45", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(640, "emphysema_45", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(641, "fibrosis_45", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(642, "pleural_thickening_45", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(643, "hernia_45", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(644, "atelectasis_46", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(645, "cardiomegaly_46", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(646, "effusion_46", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(647, "infiltration_46", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(648, "mass_46", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(649, "nodule_46", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(650, "pneumonia_46", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(651, "pneumothorax_46", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(652, "consolidation_46", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(653, "edema_46", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(654, "emphysema_46", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(655, "fibrosis_46", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(656, "pleural_thickening_46", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(657, "hernia_46", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(658, "atelectasis_47", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(659, "cardiomegaly_47", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(660, "effusion_47", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(661, "infiltration_47", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(662, "mass_47", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(663, "nodule_47", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(664, "pneumonia_47", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(665, "pneumothorax_47", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(666, "consolidation_47", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(667, "edema_47", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(668, "emphysema_47", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(669, "fibrosis_47", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(670, "pleural_thickening_47", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(671, "hernia_47", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(672, "atelectasis_48", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(673, "cardiomegaly_48", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(674, "effusion_48", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(675, "infiltration_48", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(676, "mass_48", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(677, "nodule_48", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(678, "pneumonia_48", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(679, "pneumothorax_48", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(680, "consolidation_48", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(681, "edema_48", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(682, "emphysema_48", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(683, "fibrosis_48", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(684, "pleural_thickening_48", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(685, "hernia_48", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(686, "atelectasis_49", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(687, "cardiomegaly_49", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(688, "effusion_49", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(689, "infiltration_49", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(690, "mass_49", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(691, "nodule_49", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(692, "pneumonia_49", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(693, "pneumothorax_49", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(694, "consolidation_49", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(695, "edema_49", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(696, "emphysema_49", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(697, "fibrosis_49", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(698, "pleural_thickening_49", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(699, "hernia_49", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(700, "atelectasis_50", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(701, "cardiomegaly_50", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(702, "effusion_50", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(703, "infiltration_50", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(704, "mass_50", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(705, "nodule_50", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(706, "pneumonia_50", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(707, "pneumothorax_50", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(708, "consolidation_50", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(709, "edema_50", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(710, "emphysema_50", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(711, "fibrosis_50", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(712, "pleural_thickening_50", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(713, "hernia_50", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(714, "atelectasis_51", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(715, "cardiomegaly_51", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(716, "effusion_51", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(717, "infiltration_51", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(718, "mass_51", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(719, "nodule_51", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(720, "pneumonia_51", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(721, "pneumothorax_51", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(722, "consolidation_51", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(723, "edema_51", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(724, "emphysema_51", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(725, "fibrosis_51", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(726, "pleural_thickening_51", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(727, "hernia_51", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(728, "atelectasis_52", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(729, "cardiomegaly_52", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(730, "effusion_52", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(731, "infiltration_52", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(732, "mass_52", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(733, "nodule_52", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(734, "pneumonia_52", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(735, "pneumothorax_52", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(736, "consolidation_52", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(737, "edema_52", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(738, "emphysema_52", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(739, "fibrosis_52", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(740, "pleural_thickening_52", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(741, "hernia_52", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(742, "atelectasis_53", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(743, "cardiomegaly_53", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(744, "effusion_53", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(745, "infiltration_53", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(746, "mass_53", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(747, "nodule_53", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(748, "pneumonia_53", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(749, "pneumothorax_53", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(750, "consolidation_53", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(751, "edema_53", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(752, "emphysema_53", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(753, "fibrosis_53", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(754, "pleural_thickening_53", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(755, "hernia_53", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(756, "atelectasis_54", "Atelectasis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(757, "cardiomegaly_54", "Cardiomegaly", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(758, "effusion_54", "Effusion", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(759, "infiltration_54", "Infiltration", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(760, "mass_54", "Mass", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(761, "nodule_54", "Nodule", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(762, "pneumonia_54", "Pneumonia", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(763, "pneumothorax_54", "Pneumothorax", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(764, "consolidation_54", "Consolidation", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(765, "edema_54", "Edema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(766, "emphysema_54", "Emphysema", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(767, "fibrosis_54", "Fibrosis", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(768, "pleural_thickening_54", "Pleural Thickening", "radiology", 0.0, 1.0, "normalized", False),
    FeatureDefinition(769, "hernia_54", "Hernia", "radiology", 0.0, 1.0, "normalized", False),
)

def by_key(key: str) -> FeatureDefinition:
    for value in RADIOLOGY:
        if value.key == key:
            return value
    raise KeyError(key)

def keys() -> tuple[str, ...]:
    return tuple(value.key for value in RADIOLOGY)
