from dataclasses import dataclass

@dataclass(frozen=True)
class FeatureDefinition:
    index: int
    key: str
    display: str
    group: str
    lower: float
    upper: float
    unit: str
    required: bool

TREATMENTS = (
    FeatureDefinition(0, "antimicrobial_00", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(1, "anticoagulation_00", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(2, "vasopressor_00", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(3, "fluid_resuscitation_00", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(4, "oxygen_therapy_00", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(5, "ventilation_00", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(6, "analgesia_00", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(7, "diuresis_00", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(8, "insulin_00", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(9, "renal_replacement_00", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(10, "surgery_00", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(11, "observation_00", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(12, "antimicrobial_01", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(13, "anticoagulation_01", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(14, "vasopressor_01", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(15, "fluid_resuscitation_01", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(16, "oxygen_therapy_01", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(17, "ventilation_01", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(18, "analgesia_01", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(19, "diuresis_01", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(20, "insulin_01", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(21, "renal_replacement_01", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(22, "surgery_01", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(23, "observation_01", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(24, "antimicrobial_02", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(25, "anticoagulation_02", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(26, "vasopressor_02", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(27, "fluid_resuscitation_02", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(28, "oxygen_therapy_02", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(29, "ventilation_02", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(30, "analgesia_02", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(31, "diuresis_02", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(32, "insulin_02", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(33, "renal_replacement_02", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(34, "surgery_02", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(35, "observation_02", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(36, "antimicrobial_03", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(37, "anticoagulation_03", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(38, "vasopressor_03", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(39, "fluid_resuscitation_03", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(40, "oxygen_therapy_03", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(41, "ventilation_03", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(42, "analgesia_03", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(43, "diuresis_03", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(44, "insulin_03", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(45, "renal_replacement_03", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(46, "surgery_03", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(47, "observation_03", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(48, "antimicrobial_04", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(49, "anticoagulation_04", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(50, "vasopressor_04", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(51, "fluid_resuscitation_04", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(52, "oxygen_therapy_04", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(53, "ventilation_04", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(54, "analgesia_04", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(55, "diuresis_04", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(56, "insulin_04", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(57, "renal_replacement_04", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(58, "surgery_04", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(59, "observation_04", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(60, "antimicrobial_05", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(61, "anticoagulation_05", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(62, "vasopressor_05", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(63, "fluid_resuscitation_05", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(64, "oxygen_therapy_05", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(65, "ventilation_05", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(66, "analgesia_05", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(67, "diuresis_05", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(68, "insulin_05", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(69, "renal_replacement_05", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(70, "surgery_05", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(71, "observation_05", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(72, "antimicrobial_06", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(73, "anticoagulation_06", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(74, "vasopressor_06", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(75, "fluid_resuscitation_06", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(76, "oxygen_therapy_06", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(77, "ventilation_06", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(78, "analgesia_06", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(79, "diuresis_06", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(80, "insulin_06", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(81, "renal_replacement_06", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(82, "surgery_06", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(83, "observation_06", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(84, "antimicrobial_07", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(85, "anticoagulation_07", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(86, "vasopressor_07", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(87, "fluid_resuscitation_07", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(88, "oxygen_therapy_07", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(89, "ventilation_07", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(90, "analgesia_07", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(91, "diuresis_07", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(92, "insulin_07", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(93, "renal_replacement_07", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(94, "surgery_07", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(95, "observation_07", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(96, "antimicrobial_08", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(97, "anticoagulation_08", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(98, "vasopressor_08", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(99, "fluid_resuscitation_08", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(100, "oxygen_therapy_08", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(101, "ventilation_08", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(102, "analgesia_08", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(103, "diuresis_08", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(104, "insulin_08", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(105, "renal_replacement_08", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(106, "surgery_08", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(107, "observation_08", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(108, "antimicrobial_09", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(109, "anticoagulation_09", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(110, "vasopressor_09", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(111, "fluid_resuscitation_09", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(112, "oxygen_therapy_09", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(113, "ventilation_09", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(114, "analgesia_09", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(115, "diuresis_09", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(116, "insulin_09", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(117, "renal_replacement_09", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(118, "surgery_09", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(119, "observation_09", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(120, "antimicrobial_10", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(121, "anticoagulation_10", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(122, "vasopressor_10", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(123, "fluid_resuscitation_10", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(124, "oxygen_therapy_10", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(125, "ventilation_10", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(126, "analgesia_10", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(127, "diuresis_10", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(128, "insulin_10", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(129, "renal_replacement_10", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(130, "surgery_10", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(131, "observation_10", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(132, "antimicrobial_11", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(133, "anticoagulation_11", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(134, "vasopressor_11", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(135, "fluid_resuscitation_11", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(136, "oxygen_therapy_11", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(137, "ventilation_11", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(138, "analgesia_11", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(139, "diuresis_11", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(140, "insulin_11", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(141, "renal_replacement_11", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(142, "surgery_11", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(143, "observation_11", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(144, "antimicrobial_12", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(145, "anticoagulation_12", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(146, "vasopressor_12", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(147, "fluid_resuscitation_12", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(148, "oxygen_therapy_12", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(149, "ventilation_12", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(150, "analgesia_12", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(151, "diuresis_12", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(152, "insulin_12", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(153, "renal_replacement_12", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(154, "surgery_12", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(155, "observation_12", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(156, "antimicrobial_13", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(157, "anticoagulation_13", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(158, "vasopressor_13", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(159, "fluid_resuscitation_13", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(160, "oxygen_therapy_13", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(161, "ventilation_13", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(162, "analgesia_13", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(163, "diuresis_13", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(164, "insulin_13", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(165, "renal_replacement_13", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(166, "surgery_13", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(167, "observation_13", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(168, "antimicrobial_14", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(169, "anticoagulation_14", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(170, "vasopressor_14", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(171, "fluid_resuscitation_14", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(172, "oxygen_therapy_14", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(173, "ventilation_14", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(174, "analgesia_14", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(175, "diuresis_14", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(176, "insulin_14", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(177, "renal_replacement_14", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(178, "surgery_14", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(179, "observation_14", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(180, "antimicrobial_15", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(181, "anticoagulation_15", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(182, "vasopressor_15", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(183, "fluid_resuscitation_15", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(184, "oxygen_therapy_15", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(185, "ventilation_15", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(186, "analgesia_15", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(187, "diuresis_15", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(188, "insulin_15", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(189, "renal_replacement_15", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(190, "surgery_15", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(191, "observation_15", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(192, "antimicrobial_16", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(193, "anticoagulation_16", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(194, "vasopressor_16", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(195, "fluid_resuscitation_16", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(196, "oxygen_therapy_16", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(197, "ventilation_16", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(198, "analgesia_16", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(199, "diuresis_16", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(200, "insulin_16", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(201, "renal_replacement_16", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(202, "surgery_16", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(203, "observation_16", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(204, "antimicrobial_17", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(205, "anticoagulation_17", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(206, "vasopressor_17", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(207, "fluid_resuscitation_17", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(208, "oxygen_therapy_17", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(209, "ventilation_17", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(210, "analgesia_17", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(211, "diuresis_17", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(212, "insulin_17", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(213, "renal_replacement_17", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(214, "surgery_17", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(215, "observation_17", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(216, "antimicrobial_18", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(217, "anticoagulation_18", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(218, "vasopressor_18", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(219, "fluid_resuscitation_18", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(220, "oxygen_therapy_18", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(221, "ventilation_18", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(222, "analgesia_18", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(223, "diuresis_18", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(224, "insulin_18", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(225, "renal_replacement_18", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(226, "surgery_18", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(227, "observation_18", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(228, "antimicrobial_19", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(229, "anticoagulation_19", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(230, "vasopressor_19", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(231, "fluid_resuscitation_19", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(232, "oxygen_therapy_19", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(233, "ventilation_19", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(234, "analgesia_19", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(235, "diuresis_19", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(236, "insulin_19", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(237, "renal_replacement_19", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(238, "surgery_19", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(239, "observation_19", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(240, "antimicrobial_20", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(241, "anticoagulation_20", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(242, "vasopressor_20", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(243, "fluid_resuscitation_20", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(244, "oxygen_therapy_20", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(245, "ventilation_20", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(246, "analgesia_20", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(247, "diuresis_20", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(248, "insulin_20", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(249, "renal_replacement_20", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(250, "surgery_20", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(251, "observation_20", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(252, "antimicrobial_21", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(253, "anticoagulation_21", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(254, "vasopressor_21", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(255, "fluid_resuscitation_21", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(256, "oxygen_therapy_21", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(257, "ventilation_21", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(258, "analgesia_21", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(259, "diuresis_21", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(260, "insulin_21", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(261, "renal_replacement_21", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(262, "surgery_21", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(263, "observation_21", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(264, "antimicrobial_22", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(265, "anticoagulation_22", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(266, "vasopressor_22", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(267, "fluid_resuscitation_22", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(268, "oxygen_therapy_22", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(269, "ventilation_22", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(270, "analgesia_22", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(271, "diuresis_22", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(272, "insulin_22", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(273, "renal_replacement_22", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(274, "surgery_22", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(275, "observation_22", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(276, "antimicrobial_23", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(277, "anticoagulation_23", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(278, "vasopressor_23", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(279, "fluid_resuscitation_23", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(280, "oxygen_therapy_23", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(281, "ventilation_23", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(282, "analgesia_23", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(283, "diuresis_23", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(284, "insulin_23", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(285, "renal_replacement_23", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(286, "surgery_23", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(287, "observation_23", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(288, "antimicrobial_24", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(289, "anticoagulation_24", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(290, "vasopressor_24", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(291, "fluid_resuscitation_24", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(292, "oxygen_therapy_24", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(293, "ventilation_24", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(294, "analgesia_24", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(295, "diuresis_24", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(296, "insulin_24", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(297, "renal_replacement_24", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(298, "surgery_24", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(299, "observation_24", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(300, "antimicrobial_25", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(301, "anticoagulation_25", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(302, "vasopressor_25", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(303, "fluid_resuscitation_25", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(304, "oxygen_therapy_25", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(305, "ventilation_25", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(306, "analgesia_25", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(307, "diuresis_25", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(308, "insulin_25", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(309, "renal_replacement_25", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(310, "surgery_25", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(311, "observation_25", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(312, "antimicrobial_26", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(313, "anticoagulation_26", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(314, "vasopressor_26", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(315, "fluid_resuscitation_26", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(316, "oxygen_therapy_26", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(317, "ventilation_26", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(318, "analgesia_26", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(319, "diuresis_26", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(320, "insulin_26", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(321, "renal_replacement_26", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(322, "surgery_26", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(323, "observation_26", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(324, "antimicrobial_27", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(325, "anticoagulation_27", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(326, "vasopressor_27", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(327, "fluid_resuscitation_27", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(328, "oxygen_therapy_27", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(329, "ventilation_27", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(330, "analgesia_27", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(331, "diuresis_27", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(332, "insulin_27", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(333, "renal_replacement_27", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(334, "surgery_27", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(335, "observation_27", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(336, "antimicrobial_28", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(337, "anticoagulation_28", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(338, "vasopressor_28", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(339, "fluid_resuscitation_28", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(340, "oxygen_therapy_28", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(341, "ventilation_28", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(342, "analgesia_28", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(343, "diuresis_28", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(344, "insulin_28", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(345, "renal_replacement_28", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(346, "surgery_28", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(347, "observation_28", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(348, "antimicrobial_29", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(349, "anticoagulation_29", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(350, "vasopressor_29", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(351, "fluid_resuscitation_29", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(352, "oxygen_therapy_29", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(353, "ventilation_29", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(354, "analgesia_29", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(355, "diuresis_29", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(356, "insulin_29", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(357, "renal_replacement_29", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(358, "surgery_29", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(359, "observation_29", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(360, "antimicrobial_30", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(361, "anticoagulation_30", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(362, "vasopressor_30", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(363, "fluid_resuscitation_30", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(364, "oxygen_therapy_30", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(365, "ventilation_30", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(366, "analgesia_30", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(367, "diuresis_30", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(368, "insulin_30", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(369, "renal_replacement_30", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(370, "surgery_30", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(371, "observation_30", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(372, "antimicrobial_31", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(373, "anticoagulation_31", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(374, "vasopressor_31", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(375, "fluid_resuscitation_31", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(376, "oxygen_therapy_31", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(377, "ventilation_31", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(378, "analgesia_31", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(379, "diuresis_31", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(380, "insulin_31", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(381, "renal_replacement_31", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(382, "surgery_31", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(383, "observation_31", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(384, "antimicrobial_32", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(385, "anticoagulation_32", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(386, "vasopressor_32", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(387, "fluid_resuscitation_32", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(388, "oxygen_therapy_32", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(389, "ventilation_32", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(390, "analgesia_32", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(391, "diuresis_32", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(392, "insulin_32", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(393, "renal_replacement_32", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(394, "surgery_32", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(395, "observation_32", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(396, "antimicrobial_33", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(397, "anticoagulation_33", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(398, "vasopressor_33", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(399, "fluid_resuscitation_33", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(400, "oxygen_therapy_33", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(401, "ventilation_33", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(402, "analgesia_33", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(403, "diuresis_33", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(404, "insulin_33", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(405, "renal_replacement_33", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(406, "surgery_33", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(407, "observation_33", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(408, "antimicrobial_34", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(409, "anticoagulation_34", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(410, "vasopressor_34", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(411, "fluid_resuscitation_34", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(412, "oxygen_therapy_34", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(413, "ventilation_34", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(414, "analgesia_34", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(415, "diuresis_34", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(416, "insulin_34", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(417, "renal_replacement_34", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(418, "surgery_34", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(419, "observation_34", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(420, "antimicrobial_35", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(421, "anticoagulation_35", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(422, "vasopressor_35", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(423, "fluid_resuscitation_35", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(424, "oxygen_therapy_35", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(425, "ventilation_35", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(426, "analgesia_35", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(427, "diuresis_35", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(428, "insulin_35", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(429, "renal_replacement_35", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(430, "surgery_35", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(431, "observation_35", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(432, "antimicrobial_36", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(433, "anticoagulation_36", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(434, "vasopressor_36", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(435, "fluid_resuscitation_36", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(436, "oxygen_therapy_36", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(437, "ventilation_36", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(438, "analgesia_36", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(439, "diuresis_36", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(440, "insulin_36", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(441, "renal_replacement_36", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(442, "surgery_36", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(443, "observation_36", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(444, "antimicrobial_37", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(445, "anticoagulation_37", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(446, "vasopressor_37", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(447, "fluid_resuscitation_37", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(448, "oxygen_therapy_37", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(449, "ventilation_37", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(450, "analgesia_37", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(451, "diuresis_37", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(452, "insulin_37", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(453, "renal_replacement_37", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(454, "surgery_37", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(455, "observation_37", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(456, "antimicrobial_38", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(457, "anticoagulation_38", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(458, "vasopressor_38", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(459, "fluid_resuscitation_38", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(460, "oxygen_therapy_38", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(461, "ventilation_38", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(462, "analgesia_38", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(463, "diuresis_38", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(464, "insulin_38", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(465, "renal_replacement_38", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(466, "surgery_38", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(467, "observation_38", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(468, "antimicrobial_39", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(469, "anticoagulation_39", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(470, "vasopressor_39", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(471, "fluid_resuscitation_39", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(472, "oxygen_therapy_39", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(473, "ventilation_39", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(474, "analgesia_39", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(475, "diuresis_39", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(476, "insulin_39", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(477, "renal_replacement_39", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(478, "surgery_39", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(479, "observation_39", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(480, "antimicrobial_40", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(481, "anticoagulation_40", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(482, "vasopressor_40", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(483, "fluid_resuscitation_40", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(484, "oxygen_therapy_40", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(485, "ventilation_40", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(486, "analgesia_40", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(487, "diuresis_40", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(488, "insulin_40", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(489, "renal_replacement_40", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(490, "surgery_40", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(491, "observation_40", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(492, "antimicrobial_41", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(493, "anticoagulation_41", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(494, "vasopressor_41", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(495, "fluid_resuscitation_41", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(496, "oxygen_therapy_41", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(497, "ventilation_41", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(498, "analgesia_41", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(499, "diuresis_41", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(500, "insulin_41", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(501, "renal_replacement_41", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(502, "surgery_41", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(503, "observation_41", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(504, "antimicrobial_42", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(505, "anticoagulation_42", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(506, "vasopressor_42", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(507, "fluid_resuscitation_42", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(508, "oxygen_therapy_42", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(509, "ventilation_42", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(510, "analgesia_42", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(511, "diuresis_42", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(512, "insulin_42", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(513, "renal_replacement_42", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(514, "surgery_42", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(515, "observation_42", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(516, "antimicrobial_43", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(517, "anticoagulation_43", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(518, "vasopressor_43", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(519, "fluid_resuscitation_43", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(520, "oxygen_therapy_43", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(521, "ventilation_43", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(522, "analgesia_43", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(523, "diuresis_43", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(524, "insulin_43", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(525, "renal_replacement_43", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(526, "surgery_43", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(527, "observation_43", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(528, "antimicrobial_44", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(529, "anticoagulation_44", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(530, "vasopressor_44", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(531, "fluid_resuscitation_44", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(532, "oxygen_therapy_44", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(533, "ventilation_44", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(534, "analgesia_44", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(535, "diuresis_44", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(536, "insulin_44", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(537, "renal_replacement_44", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(538, "surgery_44", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(539, "observation_44", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(540, "antimicrobial_45", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(541, "anticoagulation_45", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(542, "vasopressor_45", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(543, "fluid_resuscitation_45", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(544, "oxygen_therapy_45", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(545, "ventilation_45", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(546, "analgesia_45", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(547, "diuresis_45", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(548, "insulin_45", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(549, "renal_replacement_45", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(550, "surgery_45", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(551, "observation_45", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(552, "antimicrobial_46", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(553, "anticoagulation_46", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(554, "vasopressor_46", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(555, "fluid_resuscitation_46", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(556, "oxygen_therapy_46", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(557, "ventilation_46", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(558, "analgesia_46", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(559, "diuresis_46", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(560, "insulin_46", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(561, "renal_replacement_46", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(562, "surgery_46", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(563, "observation_46", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(564, "antimicrobial_47", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(565, "anticoagulation_47", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(566, "vasopressor_47", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(567, "fluid_resuscitation_47", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(568, "oxygen_therapy_47", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(569, "ventilation_47", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(570, "analgesia_47", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(571, "diuresis_47", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(572, "insulin_47", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(573, "renal_replacement_47", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(574, "surgery_47", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(575, "observation_47", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(576, "antimicrobial_48", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(577, "anticoagulation_48", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(578, "vasopressor_48", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(579, "fluid_resuscitation_48", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(580, "oxygen_therapy_48", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(581, "ventilation_48", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(582, "analgesia_48", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(583, "diuresis_48", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(584, "insulin_48", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(585, "renal_replacement_48", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(586, "surgery_48", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(587, "observation_48", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(588, "antimicrobial_49", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(589, "anticoagulation_49", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(590, "vasopressor_49", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(591, "fluid_resuscitation_49", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(592, "oxygen_therapy_49", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(593, "ventilation_49", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(594, "analgesia_49", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(595, "diuresis_49", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(596, "insulin_49", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(597, "renal_replacement_49", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(598, "surgery_49", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(599, "observation_49", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(600, "antimicrobial_50", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(601, "anticoagulation_50", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(602, "vasopressor_50", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(603, "fluid_resuscitation_50", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(604, "oxygen_therapy_50", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(605, "ventilation_50", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(606, "analgesia_50", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(607, "diuresis_50", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(608, "insulin_50", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(609, "renal_replacement_50", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(610, "surgery_50", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(611, "observation_50", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(612, "antimicrobial_51", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(613, "anticoagulation_51", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(614, "vasopressor_51", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(615, "fluid_resuscitation_51", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(616, "oxygen_therapy_51", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(617, "ventilation_51", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(618, "analgesia_51", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(619, "diuresis_51", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(620, "insulin_51", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(621, "renal_replacement_51", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(622, "surgery_51", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(623, "observation_51", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(624, "antimicrobial_52", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(625, "anticoagulation_52", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(626, "vasopressor_52", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(627, "fluid_resuscitation_52", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(628, "oxygen_therapy_52", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(629, "ventilation_52", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(630, "analgesia_52", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(631, "diuresis_52", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(632, "insulin_52", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(633, "renal_replacement_52", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(634, "surgery_52", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(635, "observation_52", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(636, "antimicrobial_53", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(637, "anticoagulation_53", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(638, "vasopressor_53", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(639, "fluid_resuscitation_53", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(640, "oxygen_therapy_53", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(641, "ventilation_53", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(642, "analgesia_53", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(643, "diuresis_53", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(644, "insulin_53", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(645, "renal_replacement_53", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(646, "surgery_53", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(647, "observation_53", "Observation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(648, "antimicrobial_54", "Antimicrobial", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(649, "anticoagulation_54", "Anticoagulation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(650, "vasopressor_54", "Vasopressor", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(651, "fluid_resuscitation_54", "Fluid Resuscitation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(652, "oxygen_therapy_54", "Oxygen Therapy", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(653, "ventilation_54", "Ventilation", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(654, "analgesia_54", "Analgesia", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(655, "diuresis_54", "Diuresis", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(656, "insulin_54", "Insulin", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(657, "renal_replacement_54", "Renal Replacement", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(658, "surgery_54", "Surgery", "treatments", 0.0, 1.0, "normalized", False),
    FeatureDefinition(659, "observation_54", "Observation", "treatments", 0.0, 1.0, "normalized", False),
)

def by_key(key: str) -> FeatureDefinition:
    for value in TREATMENTS:
        if value.key == key:
            return value
    raise KeyError(key)

def keys() -> tuple[str, ...]:
    return tuple(value.key for value in TREATMENTS)
