from dataclasses import dataclass

@dataclass(frozen=True)
class FeatureDefinition:
    index: int
    key: str
    display: str
    group: str
    lower: float
    upper: float
    unit: str
    required: bool

VITALS = (
    FeatureDefinition(0, "heart_rate_00", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(1, "systolic_pressure_00", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(2, "diastolic_pressure_00", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(3, "mean_arterial_pressure_00", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(4, "respiratory_rate_00", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(5, "oxygen_saturation_00", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(6, "temperature_00", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(7, "glasgow_coma_scale_00", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(8, "heart_rate_01", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(9, "systolic_pressure_01", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(10, "diastolic_pressure_01", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(11, "mean_arterial_pressure_01", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(12, "respiratory_rate_01", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(13, "oxygen_saturation_01", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(14, "temperature_01", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(15, "glasgow_coma_scale_01", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(16, "heart_rate_02", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(17, "systolic_pressure_02", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(18, "diastolic_pressure_02", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(19, "mean_arterial_pressure_02", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(20, "respiratory_rate_02", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(21, "oxygen_saturation_02", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(22, "temperature_02", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(23, "glasgow_coma_scale_02", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(24, "heart_rate_03", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(25, "systolic_pressure_03", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(26, "diastolic_pressure_03", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(27, "mean_arterial_pressure_03", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(28, "respiratory_rate_03", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(29, "oxygen_saturation_03", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(30, "temperature_03", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(31, "glasgow_coma_scale_03", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(32, "heart_rate_04", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(33, "systolic_pressure_04", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(34, "diastolic_pressure_04", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(35, "mean_arterial_pressure_04", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(36, "respiratory_rate_04", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(37, "oxygen_saturation_04", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(38, "temperature_04", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(39, "glasgow_coma_scale_04", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(40, "heart_rate_05", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(41, "systolic_pressure_05", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(42, "diastolic_pressure_05", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(43, "mean_arterial_pressure_05", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(44, "respiratory_rate_05", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(45, "oxygen_saturation_05", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(46, "temperature_05", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(47, "glasgow_coma_scale_05", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(48, "heart_rate_06", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(49, "systolic_pressure_06", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(50, "diastolic_pressure_06", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(51, "mean_arterial_pressure_06", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(52, "respiratory_rate_06", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(53, "oxygen_saturation_06", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(54, "temperature_06", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(55, "glasgow_coma_scale_06", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(56, "heart_rate_07", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(57, "systolic_pressure_07", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(58, "diastolic_pressure_07", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(59, "mean_arterial_pressure_07", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(60, "respiratory_rate_07", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(61, "oxygen_saturation_07", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(62, "temperature_07", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(63, "glasgow_coma_scale_07", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(64, "heart_rate_08", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(65, "systolic_pressure_08", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(66, "diastolic_pressure_08", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(67, "mean_arterial_pressure_08", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(68, "respiratory_rate_08", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(69, "oxygen_saturation_08", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(70, "temperature_08", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(71, "glasgow_coma_scale_08", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(72, "heart_rate_09", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(73, "systolic_pressure_09", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(74, "diastolic_pressure_09", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(75, "mean_arterial_pressure_09", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(76, "respiratory_rate_09", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(77, "oxygen_saturation_09", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(78, "temperature_09", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(79, "glasgow_coma_scale_09", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(80, "heart_rate_10", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(81, "systolic_pressure_10", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(82, "diastolic_pressure_10", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(83, "mean_arterial_pressure_10", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(84, "respiratory_rate_10", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(85, "oxygen_saturation_10", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(86, "temperature_10", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(87, "glasgow_coma_scale_10", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(88, "heart_rate_11", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(89, "systolic_pressure_11", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(90, "diastolic_pressure_11", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(91, "mean_arterial_pressure_11", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(92, "respiratory_rate_11", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(93, "oxygen_saturation_11", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(94, "temperature_11", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(95, "glasgow_coma_scale_11", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(96, "heart_rate_12", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(97, "systolic_pressure_12", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(98, "diastolic_pressure_12", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(99, "mean_arterial_pressure_12", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(100, "respiratory_rate_12", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(101, "oxygen_saturation_12", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(102, "temperature_12", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(103, "glasgow_coma_scale_12", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(104, "heart_rate_13", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(105, "systolic_pressure_13", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(106, "diastolic_pressure_13", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(107, "mean_arterial_pressure_13", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(108, "respiratory_rate_13", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(109, "oxygen_saturation_13", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(110, "temperature_13", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(111, "glasgow_coma_scale_13", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(112, "heart_rate_14", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(113, "systolic_pressure_14", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(114, "diastolic_pressure_14", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(115, "mean_arterial_pressure_14", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(116, "respiratory_rate_14", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(117, "oxygen_saturation_14", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(118, "temperature_14", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(119, "glasgow_coma_scale_14", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(120, "heart_rate_15", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(121, "systolic_pressure_15", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(122, "diastolic_pressure_15", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(123, "mean_arterial_pressure_15", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(124, "respiratory_rate_15", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(125, "oxygen_saturation_15", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(126, "temperature_15", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(127, "glasgow_coma_scale_15", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(128, "heart_rate_16", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(129, "systolic_pressure_16", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(130, "diastolic_pressure_16", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(131, "mean_arterial_pressure_16", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(132, "respiratory_rate_16", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(133, "oxygen_saturation_16", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(134, "temperature_16", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(135, "glasgow_coma_scale_16", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(136, "heart_rate_17", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(137, "systolic_pressure_17", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(138, "diastolic_pressure_17", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(139, "mean_arterial_pressure_17", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(140, "respiratory_rate_17", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(141, "oxygen_saturation_17", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(142, "temperature_17", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(143, "glasgow_coma_scale_17", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(144, "heart_rate_18", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(145, "systolic_pressure_18", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(146, "diastolic_pressure_18", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(147, "mean_arterial_pressure_18", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(148, "respiratory_rate_18", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(149, "oxygen_saturation_18", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(150, "temperature_18", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(151, "glasgow_coma_scale_18", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(152, "heart_rate_19", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(153, "systolic_pressure_19", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(154, "diastolic_pressure_19", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(155, "mean_arterial_pressure_19", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(156, "respiratory_rate_19", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(157, "oxygen_saturation_19", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(158, "temperature_19", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(159, "glasgow_coma_scale_19", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(160, "heart_rate_20", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(161, "systolic_pressure_20", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(162, "diastolic_pressure_20", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(163, "mean_arterial_pressure_20", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(164, "respiratory_rate_20", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(165, "oxygen_saturation_20", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(166, "temperature_20", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(167, "glasgow_coma_scale_20", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(168, "heart_rate_21", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(169, "systolic_pressure_21", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(170, "diastolic_pressure_21", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(171, "mean_arterial_pressure_21", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(172, "respiratory_rate_21", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(173, "oxygen_saturation_21", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(174, "temperature_21", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(175, "glasgow_coma_scale_21", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(176, "heart_rate_22", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(177, "systolic_pressure_22", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(178, "diastolic_pressure_22", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(179, "mean_arterial_pressure_22", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(180, "respiratory_rate_22", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(181, "oxygen_saturation_22", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(182, "temperature_22", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(183, "glasgow_coma_scale_22", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(184, "heart_rate_23", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(185, "systolic_pressure_23", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(186, "diastolic_pressure_23", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(187, "mean_arterial_pressure_23", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(188, "respiratory_rate_23", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(189, "oxygen_saturation_23", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(190, "temperature_23", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(191, "glasgow_coma_scale_23", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(192, "heart_rate_24", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(193, "systolic_pressure_24", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(194, "diastolic_pressure_24", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(195, "mean_arterial_pressure_24", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(196, "respiratory_rate_24", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(197, "oxygen_saturation_24", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(198, "temperature_24", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(199, "glasgow_coma_scale_24", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(200, "heart_rate_25", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(201, "systolic_pressure_25", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(202, "diastolic_pressure_25", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(203, "mean_arterial_pressure_25", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(204, "respiratory_rate_25", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(205, "oxygen_saturation_25", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(206, "temperature_25", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(207, "glasgow_coma_scale_25", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(208, "heart_rate_26", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(209, "systolic_pressure_26", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(210, "diastolic_pressure_26", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(211, "mean_arterial_pressure_26", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(212, "respiratory_rate_26", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(213, "oxygen_saturation_26", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(214, "temperature_26", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(215, "glasgow_coma_scale_26", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(216, "heart_rate_27", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(217, "systolic_pressure_27", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(218, "diastolic_pressure_27", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(219, "mean_arterial_pressure_27", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(220, "respiratory_rate_27", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(221, "oxygen_saturation_27", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(222, "temperature_27", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(223, "glasgow_coma_scale_27", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(224, "heart_rate_28", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(225, "systolic_pressure_28", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(226, "diastolic_pressure_28", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(227, "mean_arterial_pressure_28", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(228, "respiratory_rate_28", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(229, "oxygen_saturation_28", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(230, "temperature_28", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(231, "glasgow_coma_scale_28", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(232, "heart_rate_29", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(233, "systolic_pressure_29", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(234, "diastolic_pressure_29", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(235, "mean_arterial_pressure_29", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(236, "respiratory_rate_29", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(237, "oxygen_saturation_29", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(238, "temperature_29", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(239, "glasgow_coma_scale_29", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(240, "heart_rate_30", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(241, "systolic_pressure_30", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(242, "diastolic_pressure_30", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(243, "mean_arterial_pressure_30", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(244, "respiratory_rate_30", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(245, "oxygen_saturation_30", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(246, "temperature_30", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(247, "glasgow_coma_scale_30", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(248, "heart_rate_31", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(249, "systolic_pressure_31", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(250, "diastolic_pressure_31", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(251, "mean_arterial_pressure_31", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(252, "respiratory_rate_31", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(253, "oxygen_saturation_31", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(254, "temperature_31", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(255, "glasgow_coma_scale_31", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(256, "heart_rate_32", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(257, "systolic_pressure_32", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(258, "diastolic_pressure_32", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(259, "mean_arterial_pressure_32", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(260, "respiratory_rate_32", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(261, "oxygen_saturation_32", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(262, "temperature_32", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(263, "glasgow_coma_scale_32", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(264, "heart_rate_33", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(265, "systolic_pressure_33", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(266, "diastolic_pressure_33", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(267, "mean_arterial_pressure_33", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(268, "respiratory_rate_33", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(269, "oxygen_saturation_33", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(270, "temperature_33", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(271, "glasgow_coma_scale_33", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(272, "heart_rate_34", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(273, "systolic_pressure_34", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(274, "diastolic_pressure_34", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(275, "mean_arterial_pressure_34", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(276, "respiratory_rate_34", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(277, "oxygen_saturation_34", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(278, "temperature_34", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(279, "glasgow_coma_scale_34", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(280, "heart_rate_35", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(281, "systolic_pressure_35", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(282, "diastolic_pressure_35", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(283, "mean_arterial_pressure_35", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(284, "respiratory_rate_35", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(285, "oxygen_saturation_35", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(286, "temperature_35", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(287, "glasgow_coma_scale_35", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(288, "heart_rate_36", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(289, "systolic_pressure_36", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(290, "diastolic_pressure_36", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(291, "mean_arterial_pressure_36", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(292, "respiratory_rate_36", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(293, "oxygen_saturation_36", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(294, "temperature_36", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(295, "glasgow_coma_scale_36", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(296, "heart_rate_37", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(297, "systolic_pressure_37", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(298, "diastolic_pressure_37", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(299, "mean_arterial_pressure_37", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(300, "respiratory_rate_37", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(301, "oxygen_saturation_37", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(302, "temperature_37", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(303, "glasgow_coma_scale_37", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(304, "heart_rate_38", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(305, "systolic_pressure_38", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(306, "diastolic_pressure_38", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(307, "mean_arterial_pressure_38", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(308, "respiratory_rate_38", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(309, "oxygen_saturation_38", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(310, "temperature_38", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(311, "glasgow_coma_scale_38", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(312, "heart_rate_39", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(313, "systolic_pressure_39", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(314, "diastolic_pressure_39", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(315, "mean_arterial_pressure_39", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(316, "respiratory_rate_39", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(317, "oxygen_saturation_39", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(318, "temperature_39", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(319, "glasgow_coma_scale_39", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(320, "heart_rate_40", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(321, "systolic_pressure_40", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(322, "diastolic_pressure_40", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(323, "mean_arterial_pressure_40", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(324, "respiratory_rate_40", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(325, "oxygen_saturation_40", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(326, "temperature_40", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(327, "glasgow_coma_scale_40", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(328, "heart_rate_41", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(329, "systolic_pressure_41", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(330, "diastolic_pressure_41", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(331, "mean_arterial_pressure_41", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(332, "respiratory_rate_41", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(333, "oxygen_saturation_41", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(334, "temperature_41", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(335, "glasgow_coma_scale_41", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(336, "heart_rate_42", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(337, "systolic_pressure_42", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(338, "diastolic_pressure_42", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(339, "mean_arterial_pressure_42", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(340, "respiratory_rate_42", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(341, "oxygen_saturation_42", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(342, "temperature_42", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(343, "glasgow_coma_scale_42", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(344, "heart_rate_43", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(345, "systolic_pressure_43", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(346, "diastolic_pressure_43", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(347, "mean_arterial_pressure_43", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(348, "respiratory_rate_43", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(349, "oxygen_saturation_43", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(350, "temperature_43", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(351, "glasgow_coma_scale_43", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(352, "heart_rate_44", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(353, "systolic_pressure_44", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(354, "diastolic_pressure_44", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(355, "mean_arterial_pressure_44", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(356, "respiratory_rate_44", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(357, "oxygen_saturation_44", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(358, "temperature_44", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(359, "glasgow_coma_scale_44", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(360, "heart_rate_45", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(361, "systolic_pressure_45", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(362, "diastolic_pressure_45", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(363, "mean_arterial_pressure_45", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(364, "respiratory_rate_45", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(365, "oxygen_saturation_45", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(366, "temperature_45", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(367, "glasgow_coma_scale_45", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(368, "heart_rate_46", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(369, "systolic_pressure_46", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(370, "diastolic_pressure_46", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(371, "mean_arterial_pressure_46", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(372, "respiratory_rate_46", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(373, "oxygen_saturation_46", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(374, "temperature_46", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(375, "glasgow_coma_scale_46", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(376, "heart_rate_47", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(377, "systolic_pressure_47", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(378, "diastolic_pressure_47", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(379, "mean_arterial_pressure_47", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(380, "respiratory_rate_47", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(381, "oxygen_saturation_47", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(382, "temperature_47", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(383, "glasgow_coma_scale_47", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(384, "heart_rate_48", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(385, "systolic_pressure_48", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(386, "diastolic_pressure_48", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(387, "mean_arterial_pressure_48", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(388, "respiratory_rate_48", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(389, "oxygen_saturation_48", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(390, "temperature_48", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(391, "glasgow_coma_scale_48", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(392, "heart_rate_49", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(393, "systolic_pressure_49", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(394, "diastolic_pressure_49", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(395, "mean_arterial_pressure_49", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(396, "respiratory_rate_49", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(397, "oxygen_saturation_49", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(398, "temperature_49", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(399, "glasgow_coma_scale_49", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(400, "heart_rate_50", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(401, "systolic_pressure_50", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(402, "diastolic_pressure_50", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(403, "mean_arterial_pressure_50", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(404, "respiratory_rate_50", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(405, "oxygen_saturation_50", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(406, "temperature_50", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(407, "glasgow_coma_scale_50", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(408, "heart_rate_51", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(409, "systolic_pressure_51", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(410, "diastolic_pressure_51", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(411, "mean_arterial_pressure_51", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(412, "respiratory_rate_51", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(413, "oxygen_saturation_51", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(414, "temperature_51", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(415, "glasgow_coma_scale_51", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(416, "heart_rate_52", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(417, "systolic_pressure_52", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(418, "diastolic_pressure_52", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(419, "mean_arterial_pressure_52", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(420, "respiratory_rate_52", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(421, "oxygen_saturation_52", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(422, "temperature_52", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(423, "glasgow_coma_scale_52", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(424, "heart_rate_53", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(425, "systolic_pressure_53", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(426, "diastolic_pressure_53", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(427, "mean_arterial_pressure_53", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(428, "respiratory_rate_53", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(429, "oxygen_saturation_53", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(430, "temperature_53", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(431, "glasgow_coma_scale_53", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(432, "heart_rate_54", "Heart Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(433, "systolic_pressure_54", "Systolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(434, "diastolic_pressure_54", "Diastolic Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(435, "mean_arterial_pressure_54", "Mean Arterial Pressure", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(436, "respiratory_rate_54", "Respiratory Rate", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(437, "oxygen_saturation_54", "Oxygen Saturation", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(438, "temperature_54", "Temperature", "vitals", 0.0, 1.0, "normalized", False),
    FeatureDefinition(439, "glasgow_coma_scale_54", "Glasgow Coma Scale", "vitals", 0.0, 1.0, "normalized", False),
)

def by_key(key: str) -> FeatureDefinition:
    for value in VITALS:
        if value.key == key:
            return value
    raise KeyError(key)

def keys() -> tuple[str, ...]:
    return tuple(value.key for value in VITALS)
