from enum import IntEnum

class Strategy(IntEnum):
    GATHER_IMAGING = 0
    GATHER_LABS = 1
    GATHER_NOTES = 2
    EXAMINE_PATHOLOGY = 3
    REQUEST_VITALS = 4
    SPECIALIST_CONSULT = 5
    COMMIT_DECISION = 6

class Action(IntEnum):
    CHEST_RADIOGRAPH = 0
    CROSS_SECTIONAL_IMAGE = 1
    IMAGE_PRIOR = 2
    COMPLETE_BLOOD_COUNT = 3
    METABOLIC_PANEL = 4
    COAGULATION_PANEL = 5
    INFLAMMATORY_MARKERS = 6
    CARDIAC_MARKERS = 7
    ADMISSION_NOTE = 8
    PROGRESS_NOTE = 9
    DISCHARGE_SUMMARY = 10
    MEDICATION_HISTORY = 11
    WSI_OVERVIEW = 12
    WSI_REGION = 13
    PATHOLOGY_METADATA = 14
    HEART_RATE = 15
    BLOOD_PRESSURE = 16
    RESPIRATORY_RATE = 17
    OXYGENATION = 18
    TEMPERATURE = 19
    SPECIALIST_REVIEW = 20
    GUIDELINE_RETRIEVAL = 21
    COMMIT = 22
